### ISSUE TITLE
won't work on Ubuntu 13.10

### ISSUE THREAD

**Issue by rhoconlinux** [sgricci/dewdrop#16]
Hi there, when I run it on Ubuntu 13.10 x64 with python installed, it throw me this:

rho@rho-zenbook:~/Descargas$ ./dewdrop 
./dewdrop/dewdrop.py:98: Warning: /build/buildd/glib2.0-2.38.0/./gobject/gsignal.c:2475: signal 'child-added' is invalid for instance '0x292e330' of type 'GtkMenu'
not base64
./dewdrop/dewdrop.py:137: Warning: /build/buildd/glib2.0-2.38.0/./gobject/gsignal.c:2475: signal 'child-added' is invalid for instance '0x292e4d0' of type 'GtkMenu'

And then it just freeze. Any ideas?

**Comment by sgricci** [comment]
Those messages aren't indicative of any issues. Does it show up as a system tray icon?

Do you have a brand new droplr account?

If so, try uploading something via the droplr web interface.  It's a bug that's been fixed and will be out in the next release.

**Comment by rhoconlinux** [comment]
Thank you. I'm really sorry about this. I was using gnome-shell, so the tray icons are hidden, that's why I didn't saw the interface. Really nice work. 
Have a question. Is there is a way to monitor a folder? Thanks again, and sorry for the silly intervention. 
Do you mind if I make an installation script that also uses the icon on the blog?

**Comment by sgricci** [comment]
No problem. I released a beta of the next version here: http://d.pr/f/LCMv

It has a different icon than the one on the blog. You can find the source in the unstable branch. 

Also, if you have time, could you write up what you had to do to get it working on gnome-shell? Would be useful to add it to the wiki. 

—

**Comment by sgricci** [comment]
Also, there isn't currently a way to monitor a folder. But feel free to add it as an issue/suggestion. 

—

**Comment by vastbinderj** [comment]
It works in gnome-shell, you just need to unhide your tray icons with this gnome-shell extension or another like it:

https://extensions.gnome.org/extension/495/topicons/
