### ISSUE TITLE
Properly support private urls

### ISSUE THREAD

**Issue by Naatan** [sgricci/dewdrop#18]
My droplr is configured to use private url's, which dewdrop respects properly. However it copies the url without the password portion, so when I send the url to someone they have to manually enter the password, which I would need to manually retrieve, making the entire purpose of using dewdrop pointless.

It'd be nice if dewdrop, like the native droplr client, could copy private url's with the password included.

**Comment by sgricci** [comment]
Support for Private URLs (with passwords) has landed in v 0.11. You can try the beta here: http://d.pr/f/LMD4

**Comment by Naatan** [comment]
Works perfectly, thanks!!
