### ISSUE TITLE
Requirement on appindicator means it only supports Ubuntu + unity

### ISSUE THREAD

**Issue by biinari** [sgricci/dewdrop#20]

**Comment by sgricci** [comment]
That's not entirely true. Gnome Shell also uses App Indicator, and Linux Mint's Cinnamon.

Regardless, this has landed in unstable and will be in the next release. It will attempt to use AppIndicator and if it can't find it, it'll fall back to GTK StatusIcon.

I've tested on Crunchbang and it appears to work as expected.
