### ISSUE TITLE
ValueError: A 0.7-series setuptools cannot be installed with distribute

### ISSUE THREAD

**Issue by g0ddest** [sgricci/dewdrop#26]
Got this error when starting. Ubuntu 16.04 Python 2.7.11

**Comment by Aaron3** [comment]
This is a common problem, distribute was merged into setup tools. The script needs to check the version of setuptools.

**Comment by g0ddest** [comment]
Thank you for response. Can you give me some advise how to resolve this issue?

**Comment by pavelpascari** [comment]
https://github.com/sgricci/dewdrop/blob/40281f8ae098be42d40c681d9b56ea8d017461e8/pkg_resources.py#L2358

Install the newest version of setuptools on your machine.

**Comment by g0ddest** [comment]
Updated setuptools to 20.7.0 from python-setuptools package manually to 23.1.0 and it helps. Thank you!
