### ISSUE TITLE
How do I build and run?

### ISSUE THREAD

**Issue by piascikj** [sgricci/dewdrop#5]
I've forked the repo, but there's no docs on building and running the app.  How is it done?

**Comment by sgricci** [comment]
It's python, so you can run `python __main__.py` (or `./__main__.py` if you make it executable and /usr/bin/env python returns the python interpreter you want)

You'll need to replace the public key, private key and host/port (in libdroplr.py). You'll need to get those from Droplr (see the README)

**Comment by piascikj** [comment]
What about self.server?  What should it be set to?

**Comment by sgricci** [comment]
self.server should be set to the droplr API you are attempting to use.

There is a sandbox API server and a live API server.  Both of which you 
should be able to get from droplr when requresting the API keys.

--Steve

**Comment by piascikj** [comment]
Got that. Now I'm getting this error when running `python __main__.py`

```
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
    from app import App
  File "/home/jesse/projects/dewdrop/app.py", line 5, in <module>
    from config import Config
  File "/home/jesse/projects/dewdrop/config.py", line 3, in <module>
    import simplejson as json
ImportError: No module named simplejson
```

**Comment by piascikj** [comment]
Never mind the last comment.  I installed python-simplejson with apt-get.

Thanks for your help!

**Comment by sgricci** [comment]
Ok. Are you looking to develop / hack on dewdrop?

If not, you can get a pre-released build and more information at the tumblr blog for dewdrop: http://dewdropapp.tumblr.com
