### ISSUE TITLE
Feature Request: Add link to clipboard for new uploads automatically

### ISSUE THREAD

**Issue by Aaron3** [sgricci/dewdrop#6]
It would be nice to have the link to screenshots automatically copied to the clipboard.

**Comment by sgricci** [comment]
This is the way it works today (at least, for me).

Is it not working like that for you?

Also, what environment are you running this in? (Window Manager, Distro, Desktop Environment, etc.)

**Comment by Aaron3** [comment]
You're right, it is working now after a reboot. It must have been a collision with my clipboard manager or something.

Go ahead and close.

**Comment by sgricci** [comment]
Awesome!
